---
title: "Interpretation Tool"
format: docx
editor: visual
---

This document is to go over the details of the interpretation tool part of the update framework, which is based on the work by Langan et. al.

# Derivation of contours

This section will go over the derivation of forming the contours of the plot for different situations.

## Fixed-effects

We are working within the fixed-effects framework initially, where the between-study heterogeneity, denoted by $\tau^2$, is equal to zero.

### Statistical significance

Lets assume we are interested in changing the statistical significance (i.e., the p-value).

#### One new study

Let's start with assuming that there is only one new study that will be added to the meta-analysis.

The 95% confidence interval (CI) is denoted by

$$\hat{\theta} \pm \Phi^{-1} (\frac{\alpha}{2}) \sqrt{var(\hat\theta)}$$ {#eq-ci}

where $\hat\theta$ is the pooled effect estimate, $\alpha$ is the type I error rate (normally set at 0.5), $\Phi^{-1}$ is the inverse cumulative normal distribution with mean 0 and variance 1 (which ensures that $\Phi^{-1}(\alpha/2)$ maps an $\alpha$ value of 0.05 to the value of 1.96). $var(\hat\theta)$ is the variance of the pooled effect estimate.

To create a threshold for statistical significance (specified by $\alpha$), we can specify that the lower or upper bound of the 95% CI needs to touch the null value, denoted by $\theta_0$.

Let's assume that there is a new study with (unknown) effect estimate $\hat\theta_{new}$ , variance $var(\hat\theta_{new})$, and weight $w_{new}$. Then once this new study is added to the meta-analysis, the updated results will be as follows:

$$
\hat\theta = \frac{\sum^{n}_{i=1}{w_i\hat\theta_i} + w_{new}\hat\theta_{new}}{\sum^n_{i=1}{w_i} + w_{new}}
$$ {#eq-updated-estimate}

$$var(\hat\theta) = \frac{1}{\sum^n_{i=1}{w_i} + w_{new}}$$ {#eq-updated-variance}

where $n$ is the number of studies in the original meta-analysis.

By substituting @eq-updated-estimate and @eq-updated-variance into @eq-ci, and specifying that the upper or lower bound equals $\theta_0$, we can get an expression for $\theta_{new}$ in terms of other quantities:

$$
\hat\theta_{new} = \frac{1}{w_{new}}\{\theta_0[\sum^n_{i=1}{w_i} + w_{new}] - \sum^n_{i=1}{w_i \hat\theta_i} \pm \Phi^{-1}(\frac{\alpha}{2}) \sqrt{\sum^n_{i=1}{w_i} + w_{new}}\}
$$ {#eq-rearranged-theta-new}

In a fixed-effects meta-analysis, each weight is simply calculated as

$$
w_i = \frac{1}{var(\hat\theta_i)}
$$ {#eq-fixed-weight}

Therefore, by substituting @eq-fixed-weight into @eq-rearranged-theta-new, we then get an equation for the contour threshold on the estimate-variance plane.

#### Two new studies

When expanding from one new study to two new studies, @eq-updated-estimate and @eq-updated-variance become

$$
\hat\theta = \frac{\sum^{n}_{i=1}{w_i\hat\theta_i} + w_{n1}\hat\theta_{n1} + w_{n2}\hat\theta_{n2}}{\sum^n_{i=1}{w_i} + w_{n1} + w_{n2}}
$$ {#eq-meta-theta-2studies}

$$var(\hat\theta) = \frac{1}{\sum^n_{i=1}{w_i} + w_{n1} + w_{n2}}$$ {#eq-meta-variance-2studies}

where $\hat\theta_{nj}$ and $w_{nj}$ are the estimates and weights of new studies respectively, where $j = 1,2$.

Let

$$w_{new} = w_{n1} + w_{n2}$$ {#eq-weight-2studies}

$$\hat\theta_{new} = \frac{w_{n1}\hat\theta_{n1} + w_{n2}\hat\theta_{n2}}{w_{n1} + w_{n2}}$$ {#eq-theta-2studies} Substituting @eq-weight-2studies and @eq-theta-2studies into @eq-meta-theta-2studies and @eq-meta-variance-2studies brings us back to equations @eq-updated-estimate and @eq-updated-variance. Therefore, everything else follows through as before, but with new definitions for $w_{new}$ and $\hat\theta_{new}$.

#### Multiple new studies

Where we are calculating the contour to $m$ new studies, the equations follow as if it was one new study, but $w_{new}$ and $\hat\theta_{new}$ are defined as

$$
w_{new} = \sum^m_{j=1}{w_{nj}}
$$

$$
\hat\theta_{new} = \frac{\sum^m_{j=1}{w_{nj}\hat\theta_{nj}}}{\sum^m_{j=1}{w_{nj}}}
$$

where $\hat\theta_{nj}$ and $w_{nj}$ are the estimates and weights of the new studies respectively, for $j = 1,2,...,m$.

### Specific confidence interval bounds

Let's suppose that instead of wanting a statistically significant pooled estimate, that the researchers are looking for the 95% CI bounds to be at a certain value (likely of clinical importance).

With statistical significance, the contour equations are calculated from stating that the upper or lower bounds must touch the null value, $\theta_0$. In this scenario, the contour equations would be calculated from the following thresholds:

$$
\theta_{lower} = \hat{\theta} - \Phi^{-1} (\frac{\alpha}{2}) \sqrt{var(\hat\theta)}
$$ {#eq-lower-bound}

$$
\theta_{upper} = \hat{\theta} + \Phi^{-1} (\frac{\alpha}{2}) \sqrt{var(\hat\theta)}
$$ {#eq-upper-bound}

where $\theta_{lower}$ and $\theta_{upper}$ are the user-defined lower and upper 95% CI bounds of interest.

Substituting @eq-updated-estimate and @eq-updated-variance into @eq-lower-bound and @eq-upper-bound, and rearranging gives the following expression(s) for $\hat\theta_{new}$.

$$
\hat\theta_{new} = \frac{1}{w_{new}}\{\theta_{lower}[\sum^n_{i=1}{w_i} + w_{new}] - \sum^n_{i=1}{w_i \hat\theta_i} + \Phi^{-1}(\frac{\alpha}{2}) \sqrt{\sum^n_{i=1}{w_i} + w_{new}}\}
$$ $$
\hat\theta_{new} = \frac{1}{w_{new}}\{\theta_{upper}[\sum^n_{i=1}{w_i} + w_{new}] - \sum^n_{i=1}{w_i \hat\theta_i} - \Phi^{-1}(\frac{\alpha}{2}) \sqrt{\sum^n_{i=1}{w_i} + w_{new}}\}
$$

Whilst in the fixed-effects framework, the extensions to multiple new studies is the same here as for statistical significance.

## Random-effects

When working in the random-effects framework things get more complex as $\tau^2 \ne 0$ and is estimated from the studies in the meta-analysis, including the new studies.

Let's start again with only considering one new study and aiming for a meta-analysis with statistical significance at the $\alpha = 0.05$ level.

Under a random-effects framework, the weight for each study is instead calculated as

$$
w_i = \frac{1}{var(\hat\theta_i) + \tau^2}
$$ {#eq-random-weight}

Unfortunately, $\tau^2$, the between-study heterogeneity which is calculated from all studies, is too complicated to estimate by hand, and so researchers often use established estimators instead, such as the DerSimonian-Laird estimator or Restricted Maximum Likelihood.

As such, an equation to form the contour thresholds cannot be derived as was done for the fixed-effects framework. Instead, as per Langan et. al., the standard error-estimate plane is broken down into 'pixels', where $\tau^2$ is estimated at each pixel (calculated from the original studies as well as the new study represented by the pixel). For each pixel, $\tau^2$ value, $\hat\theta_{new}$, and $var(\hat\theta_{new})$ are plugged into the meta-analysis equations ( @eq-updated-estimate and @eq-updated-variance), but using the weights calculated in @eq-random-weight, and noted whether or not the threshold was crossed (i.e. whether 95% CI was one side of null effect). The result at each pixel is coloured according to whether the threshold was met. This easily extends to the clinical bound thresholds as well as the statistical significance.

### Multiple new studies

Under the fixed-effects model, the weighted sum of the new studies became the point that visually represented whether the updated meta-analysis was in a certain zone (as created by the contours). This worked because the lack of between-study heterogeneity simplified the maths to weighted averages (see [Multiple new studies]).

Under the random-effects model, we have to take the estimate-variance plane 'pixel-by-pixel'. When there was one new study, this was simple as the pixel had one set of possible values 'attached' to it that were easily obtained. When considering multiple new studies, the idea of using the 'average' of the new studies doesn't work, as we cannot know from what new studies created the 'average' represented by the pixel. Furthermore, there would be no way of estimating $\tau^2$ without estimates of the new studies represented by the 'average'. For a single pixel representing the new studies 'average', without the new studies data, there could be multiple values of $\tau^2$.

**We have to assume a constant** $\tau^2$ **across all pixels in the plane.**

The estimated between-study heterogeneity from the updated meta-analysis is proposed as the common $\tau^2$ across all pixels. Whilst this may be a strong assumption as you get to more 'extreme' pixels/values, the new studies 'average' would at least sit in the correct section of the plot (as per the fixed-effects).

The new studies 'average' that would be plotted (in addition to all the new studies) would be calculated as

$$\hat\theta_{\bar{new}} = \frac{\sum^m_{j=1}{\frac{\hat\theta_{nj}}{var(\hat\theta_{nj}) + \tau^2}}}{\sum^m_{j=1}{\frac{1}{var(\hat\theta_{nj}) + \tau^2}}}$$
$$var(\hat\theta_{\bar{new}}) = 1/\sum^m_{j=1}\frac{1}{var(\hat\theta_{nj}) + \tau^2}$$
where $m$ is the number of new studies and $\hat\theta_{nj}$ is the jth new study where $j = 1, ..., m$.

Then for each pixel, the updated pooled effect estimate and associated 95% confidence interval is calculated using equations @eq-updated-estimate, @eq-updated-variance and @eq-random-weight, where $\tau^2$ is the value from the updated meta-analysis from adding known new studies. As per the scenario with one new study, each pixel is coloured according to whether the specified threshold was met.

A potential extension, depending on time and resources, could be to estimate $\tau^2$ at each pixel by simulating $m$ new studies. This decision depends on the balance between computational resource and improving the approximation of $\tau^2$. In the current scenario, I feel that the assumption above is satisfactory - but this may change depending on how the plot's use is extended.
